using System;
using System.Collections.Generic;
using MediatR;
using AskEiva.Domain.Repositories;

namespace AskEiva.Application.QualityAssurance.Commands;

/// <summary>
/// MediatR command to execute an automated quality assurance evaluation suite against the active RAG pipeline.
/// </summary>
/// <param name="TestSuite">The collection of predefined test cases containing queries and ground truth metrics to evaluate.</param>
public record ExecutePipelineEvaluationCommand(List<EvaluationTestCase> TestSuite) : IRequest<EvaluationSummaryReport>;

/// <summary>
/// Represents a single testing scenario used to benchmark pipeline accuracy.
/// </summary>
/// <param name="Query">The diagnostic search question or user prompt to submit.</param>
/// <param name="ExpectedContextKeys">The list of target documentation IDs or chunk keys that the search engine ought to retrieve.</param>
/// <param name="GroundTruthAnswer">The verified, ideal reference answer used to grade the generated response.</param>
public record EvaluationTestCase(string Query, List<string> ExpectedContextKeys, string GroundTruthAnswer);

/// <summary>
/// Defines the overall performance metrics gathered after executing a complete evaluation test suite.
/// </summary>
/// <param name="AverageContextPrecision">The average accuracy score measuring how relevant the retrieved context chunks were across all tests.</param>
/// <param name="AverageAnswerFaithfulness">The average consistency score measuring how factually grounded the generated answers were in the retrieved context.</param>
/// <param name="DetailedResults">The individual row-by-row tracking outcomes for every executed test case.</param>
public record EvaluationSummaryReport(double AverageContextPrecision, double AverageAnswerFaithfulness, List<EvaluationRowResult> DetailedResults);

/// <summary>
/// Represents the granular testing metrics and generation outputs for an individual test case execution.
/// </summary>
/// <param name="Query">The original input question evaluated during the test pass.</param>
/// <param name="ContextPrecisionScore">The calculated accuracy score for the retrieval phase of this specific query.</param>
/// <param name="FaithfulnessScore">The calculated factual truthfulness score for the generation phase of this specific query.</param>
/// <param name="GeneratedAnswer">The actual text response generated by the AI model during the test run.</param>
/// <param name="PassedStrictVersionCheck">True if the response honors specific product version boundaries specified in the test profile.</param>
public record EvaluationRowResult(string Query, double ContextPrecisionScore, double FaithfulnessScore, string GeneratedAnswer, bool PassedStrictVersionCheck);

/// <summary>
/// MediatR command to submit user reinforcement feedback (thumbs up/down or swipe actions) to optimize dataset biases over time.
/// </summary>
/// <param name="Query">The original user prompt or search query that generated the response.</param>
/// <param name="GeneratedAnswer">The specific answer text produced by the platform that is being graded.</param>
/// <param name="IsApproved">True if the user approved the response quality, false if rejected.</param>
/// <param name="TargetCollectionBias">The deployment target profile classification tracking where the interaction occurred (e.g., "ClosedBaseline", "LiveOpenAssist").</param>
/// <param name="CorrectionNotes">Optional textual notes or manual corrections provided by an administrator or engineer.</param>
public record SubmitSwipeFeedbackCommand(
    string Query, 
    string GeneratedAnswer, 
    bool IsApproved, 
    string TargetCollectionBias, 
    string CorrectionNotes = ""
) : IRequest<bool>;