using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using AskEiva.Domain.Repositories;
using MediatR;

namespace AskEiva.Application.Telemetry.Queries;

/// <summary>
/// MediatR query to fetch system counts and recent user interaction logs for dashboard display panels.
/// </summary>
public record GetDashboardTelemetryQuery : IRequest<TelemetryDashboardResult>;

/// <summary>
/// Wraps the statistical counters and log history items returned for user interface visualization tracking components.
/// </summary>
/// <param name="TotalUniqueDocuments">The count of unique reference documents saved in the system database.</param>
/// <param name="TotalUniqueTickets">The total number of original support tickets indexed.</param>
/// <param name="TotalSoftwareReleases">The number of individual software release version files tracked.</param>
/// <param name="TotalSoftwareReleaseChunks">The total aggregated count of split text chunks derived from release files.</param>
/// <param name="TotalGraphContextChains">The total number of distilled relational knowledge chains stored.</param>
/// <param name="Logs">The list of converted user interaction histories and feedback status labels.</param>
public record TelemetryDashboardResult(
    int TotalUniqueDocuments,
    int TotalUniqueTickets,
    int TotalSoftwareReleases,
    int TotalSoftwareReleaseChunks, 
    int TotalGraphContextChains,
    List<InteractionLogItemDto> Logs
);

/// <summary>
/// Represents a structured log record documenting a single user conversation instance with the system.
/// </summary>
/// <param name="Timestamp">The universal date and time when the query transaction took place.</param>
/// <param name="UserPrompt">The plain-text search string submitted by the user query.</param>
/// <param name="CopilotResponse">The text response generated by the system back to the user interface.</param>
/// <param name="ModelUsed">The specific artificial intelligence foundation model string that processed the generation pass.</param>
/// <param name="FeedbackState">A formatted status tag showing the success state or validation outcome of the session.</param>
public record InteractionLogItemDto(
    DateTime Timestamp, 
    string UserPrompt, 
    string CopilotResponse, 
    string ModelUsed,
    string FeedbackState
);

/// <summary>
/// Handles the dashboard telemetry query by concurrently fetching count statistics across diverse collection tables 
/// and decoding raw interaction logs from storage.
/// </summary>
public class GetDashboardTelemetryQueryHandler : IRequestHandler<GetDashboardTelemetryQuery, TelemetryDashboardResult>
{
    private readonly IKnowledgeRetrievalRepository _retrievalRepository;

    /// <summary>
    /// Initializes a new instance of the handler using the necessary database retrieval interface.
    /// </summary>
    /// <param name="retrievalRepository">The search repository used to run counters and extract log files.</param>
    public GetDashboardTelemetryQueryHandler(IKnowledgeRetrievalRepository retrievalRepository)
    {
        _retrievalRepository = retrievalRepository;
    }

    /// <summary>
    /// Dispatches database counters in parallel to minimize performance blockages, processes JSON arrays, 
    /// and formats raw data fields for the frontend.
    /// </summary>
    /// <param name="request">The query parameters execution instruction payload.</param>
    /// <param name="cancellationToken">Token utilized to monitor and safely interrupt background tasks.</param>
    /// <returns>A unified telemetry result containing system counts and processed user interaction logs.</returns>
    public async Task<TelemetryDashboardResult> Handle(GetDashboardTelemetryQuery request, CancellationToken cancellationToken)
    {
        // Define tracking task operations to extract statistical counts across database collections
        var docsTask = _retrievalRepository.GetDistinctSourceCountAsync("DocumentationLibrary", "document_id");
        var ticketsTask = _retrievalRepository.GetDistinctSourceCountAsync("KnowledgeNode", "source_id"); 
        var releaseTask = _retrievalRepository.GetDistinctSourceCountAsync("SoftwareReleaseNode", "full_version_title"); 
        var graphChainsTask = _retrievalRepository.GetDistinctSourceCountAsync("GraphContextChain", "ticket_id");
        var releaseChunksTask = _retrievalRepository.GetTotalClassCountAsync("SoftwareReleaseNode");
        
        // Fetch the raw user interaction data logs block
        var logsTask = _retrievalRepository.GetRawInteractionLogsAsync(limit: 500);

        // Execute background count operations concurrently to optimize query processing times
        await Task.WhenAll(docsTask, ticketsTask, releaseTask, releaseChunksTask, graphChainsTask);

        var logsResult = await logsTask;
        var activeLogs = new List<InteractionLogItemDto>();

        // Safe check and extraction pass of the raw JSON dictionary object tree elements
        if (logsResult.ValueKind != JsonValueKind.Undefined &&
            logsResult.TryGetProperty("data", out var data) &&
            data.TryGetProperty("Get", out var get) &&
            get.TryGetProperty("InteractionLog", out var logArray) &&
            logArray.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in logArray.EnumerateArray())
            {
                string queryText = item.TryGetProperty("query", out var q) ? q.GetString() ?? "" : "";
                string answerText = item.TryGetProperty("answer", out var a) ? a.GetString() ?? "" : "";
                
                bool successful = item.TryGetProperty("was_successful", out var ws) && ws.GetBoolean();
                string feedbackLabel = successful ? "👍 Success" : "❌ Issue / Conflict";

                DateTime logTime = DateTime.UtcNow;
                if (item.TryGetProperty("timestamp", out var ts) && DateTime.TryParse(ts.GetString(), out var parsedTime))
                {
                    logTime = parsedTime;
                }

                // Map raw properties into standard data transfer objects for presentation layers
                activeLogs.Add(new InteractionLogItemDto(
                    Timestamp: logTime,
                    UserPrompt: queryText,
                    CopilotResponse: answerText,
                    ModelUsed: "mistral-large-latest",
                    FeedbackState: feedbackLabel
                ));
            }
        }

        // Return the accumulated counters and formatted interaction histories
        return new TelemetryDashboardResult(
            TotalUniqueDocuments: docsTask.Result,
            TotalUniqueTickets: ticketsTask.Result, 
            TotalSoftwareReleases: releaseTask.Result,
            TotalSoftwareReleaseChunks: releaseChunksTask.Result,
            TotalGraphContextChains: graphChainsTask.Result,
            Logs: activeLogs
        );
    }
}