using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AskEiva.Domain.Repositories;
using AskEiva.Domain.Services; 
using AskEiva.Domain.Utilities;
using AskEiva.Domain.Entities;
using MediatR;

namespace AskEiva.Application.Documentation.Commands;

/// <summary>
/// MediatR command to trigger the data ingestion process for specific documentation categories.
/// </summary>
/// <param name="CategoryIds">The list of external category identifiers to target for scraping and ingestion.</param>
public record IngestDocumentationCommand(List<string> CategoryIds) : IRequest<DocIngestionResult>;

/// <summary>
/// Represents the result metrics of a documentation ingestion process execution.
/// </summary>
/// <param name="ArticlesProcessed">The total number of individual articles or pages parsed during the run.</param>
/// <param name="TotalChunksCreated">The total number of text segments generated by the text splitter tool.</param>
/// <param name="Success">Indicates if the ingestion process completed without breaking faults.</param>
/// <param name="Message">A descriptive summary containing execution status details.</param>
public record DocIngestionResult(int ArticlesProcessed, int TotalChunksCreated, bool Success, string Message);

/// <summary>
/// Coordinates the process of downloading external documentation, breaking it into manageable segments, 
/// and saving those chunks into the vector storage engine.
/// </summary>
public class IngestDocumentationCommandHandler : IRequestHandler<IngestDocumentationCommand, DocIngestionResult>
{
    private readonly IDocumentationCrawler _crawler; 
    private readonly IDocumentationRepository _repository;

    /// <summary>
    /// Initializes a new instance of the handler with necessary data source and storage abstractions.
    /// </summary>
    /// <param name="crawler">The external data crawling service provider.</param>
    /// <param name="repository">The target knowledge storage repository interface.</param>
    public IngestDocumentationCommandHandler(IDocumentationCrawler crawler, IDocumentationRepository repository)
    {
        _crawler = crawler;
        _repository = repository;
    }

    /// <summary>
    /// Processes the ingestion request by looping through target categories, streaming source documents, 
    /// segmenting contents, and pushing batches to vector storage.
    /// </summary>
    /// <param name="request">The ingestion instruction containing target category targets.</param>
    /// <param name="cancellationToken">Token utilized to monitor and safely interrupt background tasks.</param>
    /// <returns>A data object containing process tracking counts and success states.</returns>
    public async Task<DocIngestionResult> Handle(IngestDocumentationCommand request, CancellationToken cancellationToken)
    {
        int articlesCount = 0;
        int totalChunksCount = 0;
        
        // Initialize the text splitter utility with targeted configurations for technical documentation text
        var splitter = new TextSplitter(chunkSize: 1000, chunkOverlap: 200); 

        foreach (var categoryId in request.CategoryIds)
        {
            if (cancellationToken.IsCancellationRequested) break;

            // Stream parsed document units asynchronously from the targeted crawler route
            await foreach (var node in _crawler.CrawlSolutionsAsync(categoryId).WithCancellation(cancellationToken))
            {
                Console.WriteLine("\n==================================================");
                Console.WriteLine($"🔍 [DIAGNOSTIC] Processing Article #{articlesCount + 1}");
                Console.WriteLine($"   Title: {node.Title}");
                Console.WriteLine($"   Raw Length: {node.Content?.Length ?? 0} characters");
                Console.WriteLine("==================================================");

                if (string.IsNullOrWhiteSpace(node.Content))
                {
                    Console.WriteLine("   ⚠️ [DIAGNOSTIC WARNING] Content is completely NULL or Empty! Skipping.");
                    articlesCount++;
                    continue;
                }

                // Segment the raw content text into structured data pieces for vector database storage
                var splits = splitter.SplitDocumentation(node).ToList();
                
                Console.WriteLine($"   📊 [DIAGNOSTIC RESULT] Splits Produced: {splits.Count}");
                
                if (splits.Any())
                {
                    // Inspect the first two chunks to verify character extraction quality in console outputs
                    foreach (var chunk in splits.Take(2)) 
                    {
                        Console.WriteLine($"      -> Chunk ID: {chunk.ChunkId}");
                        Console.WriteLine($"         Text Excerpt ({chunk.Content.Length} chars): \"{(chunk.Content.Length > 80 ? chunk.Content.Substring(0, 80) + "..." : chunk.Content)}\"");
                    }
                    if (splits.Count > 2)
                    {
                        Console.WriteLine($"      ... and {splits.Count - 2} more chunks.");
                    }

                    // Direct vector ingestion pass using categorical tags for granular query filtering
                    await _repository.BatchIngestDocChunksAsync(splits, documentType: node.Category, globalTags: new() { node.Category, "ManualAsset" });
                    
                    totalChunksCount += splits.Count;
                }
                else
                {
                    Console.WriteLine("   ❌ [DIAGNOSTIC ALERT] Split documentation returned ZERO chunks for this article!");
                }
                
                articlesCount++;
            }
        }

        return new DocIngestionResult(articlesCount, totalChunksCount, true, "Diagnostic run finished.");
    }
}