using System;
using System.Collections.Generic;

namespace AskEiva.Domain.Entities;

/// <summary>
/// Represents a structured log record capturing human-in-the-loop feedback and system responses for quality assurance tracking.
/// </summary>
public class EvaluationFeedbackLog
{
    /// <summary>
    /// Gets or sets the unique primary identifier tracking this specific feedback log entry.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the original search question or prompt submitted to the system pipeline.
    /// </summary>
    public string Query { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the conversational text answer generated by the system during the interaction instance.
    /// </summary>
    public string ProposedAnswer { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a value indicating whether an administrator or end-user approved the quality of the generated response.
    /// </summary>
    public bool IsApproved { get; set; }

    /// <summary>
    /// Gets or sets optional manual notes, corrections, or adjustments provided by the reviewer.
    /// </summary>
    public string CorrectionNotes { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the deployment tracking category or testing profile variant where this interaction occurred.
    /// </summary>
    public string Phase { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the universal date and time stamp indicating exactly when this log entry was saved.
    /// </summary>
    public DateTime LoggedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the verified, ideal closing resolution or reference answer used to grade the system response.
    /// </summary>
    public string GroundTruth { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the collection of supporting text documentation chunks and release notes retrieved to ground this response.
    /// </summary>
    public List<string> Context { get; set; } = new();
}