namespace AskEiva.Domain.ValueObjects;

/// <summary>
/// Represents an unalterable conversation turn boundary within an active user session layout.
/// </summary>
/// <param name="MessageText">The raw plain-text message string submitted by the participant.</param>
/// <param name="IsUser">True if the text message originated from an active end-user, false if generated by the AI platform assistant.</param>
public record ChatTurn(string MessageText, bool IsUser);