using System.Collections.Generic;
using System.Threading.Tasks;
using AskEiva.Domain.Entities;
using AskEiva.Domain.ValueObjects;

namespace AskEiva.Domain.Services;

/// <summary>
/// Defines the core orchestration layer contract responsible for synthesizing multi-source context matrices 
/// and prompting large language models to generate accurate, factually-grounded answers.
/// </summary>
public interface ILlmOrchestrationService
{
    /// <summary>
    /// Aggregates retrieved text segments and structural knowledge graph paths into a unified prompt context 
    /// to generate a comprehensive plain-text answer to a user question.
    /// </summary>
    /// <param name="userQuestion">The natural language search question or technical problem statement submitted by the user.</param>
    /// <param name="semanticContext">The collection of plain-text documentation chunks retrieved via vector similarity search paths.</param>
    /// <param name="structuralGraphMashes">The sequence of distilled graph context chain entities providing relational cross-references.</param>
    /// <returns>A clean, descriptive plain-text response generated by the underlying model engine.</returns>
    Task<string> DistillContextIntoAnswerAsync(
        string userQuestion, 
        IEnumerable<RetrievalMatch> semanticContext, 
        IEnumerable<GraphContextChain> structuralGraphMashes
    );
}