using System.Collections.Generic;
using System.Threading.Tasks;

namespace AskEiva.Domain.Services;

/// <summary>
/// Defines the GraphRAG compiler service contracts tasked with calling Mistral AI infrastructure 
/// to distill text entities down into structural graph triples, paths, and metadata summaries.
/// </summary>
public interface IMistralDistillationService
{
    /// <summary>
    /// Evaluates a support ticket against a collection of metadata candidate blocks to compile a structured graph relationship chain.
    /// </summary>
    /// <param name="ticketId">The unique identification key of the anchor support ticket.</param>
    /// <param name="ticketBody">The stitched, full conversational text timeline of the support ticket.</param>
    /// <param name="candidatesContext">The background documentation or release note text snippets evaluated for structural links.</param>
    /// <returns>A structured compilation response model containing extracted product targets, edge predicates, and text chains.</returns>
    Task<ChainCompilationResponse> CompileContextChainAsync(string ticketId, string ticketBody, string candidatesContext);
    
    /// <summary>
    /// Runs a binary correlation analysis between a single ticket entity and an individual reference item to calculate edge relationship weights.
    /// </summary>
    /// <param name="ticketContent">The plain-text data representing the target support ticket node.</param>
    /// <param name="referenceContent">The plain-text content of the candidate reference node being cross-examined.</param>
    /// <param name="collectionType">The collection archetype name of the reference target (e.g., "DocumentLibrary").</param>
    /// <returns>A targeted distillation decision model outlining relationship connectivity status and structural predicates.</returns>
    Task<DistillationDecision> AnalyzeRelationshipAsync(string ticketContent, string referenceContent, string collectionType);
}

/// <summary>
/// Holds the structured knowledge graph payload parameters extracted by the model during a GraphRAG compilation pass.
/// </summary>
public class ChainCompilationResponse
{
    /// <summary>
    /// Gets or sets a value indicating whether a strong, verifiable semantic connection exists between the analyzed text profiles.
    /// </summary>
    public bool IsLinked { get; set; } = false;

    /// <summary>
    /// Gets or sets the primary software application name context discovered during the text evaluation (e.g., "NaviPac").
    /// </summary>
    public string MainProductContext { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the functional problem scenario classification assigned to this relationship link.
    /// </summary>
    public string ScenarioType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the continuous, formatted semantic path string representing the visual relationship loop.
    /// </summary>
    public string SharedPathChain { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the sequence of individual action verbs or structural predicates parsed out of the generated chain.
    /// </summary>
    public List<string> Predicates { get; set; } = new();

    /// <summary>
    /// Gets or sets an AI-generated analytical summary tracking how this specific path overlaps with environmental parameters.
    /// </summary>
    public string EnvironmentalContextSummary { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the mathematical accuracy probability assigned by the model when extracting these data elements.
    /// </summary>
    public double ConfidenceScore { get; set; } = 0.0;
}

/// <summary>
/// Holds the binary relationship connection status and edge assignment flags computed during a standalone text correlation check.
/// </summary>
public class DistillationDecision
{
    /// <summary>
    /// Gets or sets a value indicating whether a semantic bridge exists between the evaluated records.
    /// </summary>
    public bool IsLinked { get; set; } = false;

    /// <summary>
    /// Gets or sets the targeted network verb predicate defining the relationship bridge characterization (defaults to "RELATED_TO").
    /// </summary>
    public string ExtractedPredicate { get; set; } = "RELATED_TO";

    /// <summary>
    /// Gets or sets the accuracy confidence calculation value score generated by the model.
    /// </summary>
    public double ConfidenceScore { get; set; } = 0.0;
}